eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082
spring:
  application:
    name: service-feign
  thymeleaf:
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
  main:
      allow.bean.definition.overriding: true

feign:
  hystrix:
    enabled: true