eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8088
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /gr/**/**
      serviceId: service-feign
    api-b:
      path: /sj/**/**
      serviceId: service-feign-business
    api-c:
      path: /ht/**/**
      serviceId: service-feign-backstage
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000