server:
  port: 8081

spring:
  application:
    name: service-provider
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1809b8?ServerTimeZone=HongKong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml

